obj-$(CONFIG_SMAF) += smaf-core.o
obj-$(CONFIG_SMAF_CMA) += smaf-cma.o
obj-$(CONFIG_SMAF_OPTEE_ALLOCATOR) += smaf-optee-allocator.o
obj-$(CONFIG_SMAF_TEST_SECURE) += smaf-testsecure.o
obj-$(CONFIG_SMAF_OPTEE) += smaf-tee.o
